### ISSUE TITLE
Bot DMs when no matching appointments exist

### ISSUE THREAD

**Issue by ivanoblomov** [ivanoblomov/vaccinesignup#1]
DM says:
```
Appointments now available at:
```

**Comment by ivanoblomov** [comment]
Captured by 3a04ef8e7d8d3d33dccb47c94fc984b40257029c.

**Comment by ivanoblomov** [comment]
Fixed by a253dfa20783f1883ae7615bff5e05251b1351de.

**Comment by wraasch** [comment]
Just received a DM containing an empty appointment:

![BE21E4DF-C345-4EE6-B915-FCCE4C633E59](https://user-images.githubusercontent.com/62122864/113359820-6c857980-92fd-11eb-9a8f-665cd8751402.png)

Do you think this is because the text is now `Check eligibility and sign-up at`?

**Comment by ivanoblomov** [comment]
Doh! I think it's because `Location#link` is an empty string...
```ruby
[5] pry(main)> Location.where("addr1 LIKE '2515 Alta%'").first.link
  Location Load (0.7ms)  SELECT "locations".* FROM "locations" WHERE (addr1 LIKE '2515 Alta%') ORDER BY "locations"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> ""
```
and the [conditional treats that as true](https://github.com/ivanoblomov/vaccinesignup/blob/main/app/models/location.rb#L49).

This is a quick fix. Let me open a PR.

**Comment by ivanoblomov** [comment]
@wraasch confirmed the fix:
![Screen Shot 2021-04-02 at 1 20 00 AM](https://user-images.githubusercontent.com/113809/113383510-15f65a80-9352-11eb-94fc-414db81f3818.png)
Note that without a link or a phone number though, the user would have to google the place.
